=== DiogoRio/DAW2020/T2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Title (bold) >

<!ELEMENT Main_Title (Title) >

<!ELEMENT  Header (list_header) >

<!ELEMENT list_header (header_item)* >

<!ELEMENT header_item (Subtitle,text)>

<!ELEMENT Subtitle (bold) >

<!ELEMENT Workteam (Title,list_names) >

<!ELEMENT list_names (names)* >

<!ELEMENT names (name, id, email, link?) >

<!ELEMENT name (#PCDATA)* >

<!ELEMENT id (#PCDATA)* >

<!ELEMENT email (#PCDATA)* >

<!ELEMENT link (#PCDATA)* >

<!ELEMENT bold (#PCDATA)* >

<!ELEMENT italic (#PCDATA)* >

<!ELEMENT Abstract (Title,paragraph*) >

<!ELEMENT list_link (link_item)* >

<!ELEMENT link_item (link) >

<!ELEMENT Deliverables (Title,list_link) >

<!ELEMENT text ( #PCDATA | link | italic | bold | name | id | email)* >

<!ELEMENT paragraph (text)+ >

<!ELEMENT project_record (Main_Title, Header, Workteam, Abstract, Deliverables) >

=== DiogoRio/DAW2020/T2/Untitled.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project_record SYSTEM "pr.dtd">
<?xml-stylesheet type="text/css" href="Untitled1.css"?> 
<project_record>
    <Main_Title>
        <Title>
            <bold>PROJECT RECORD</bold>
        </Title>
    </Main_Title>
    <Header>
        <list_header>
            <header_item>
                <Subtitle>
                    <bold> KEY_NAME</bold>
                </Subtitle>
                <text>PED_MICEI2002_TESES</text>
            </header_item>
            
            <header_item>
                <Subtitle>
                    <bold> KEY_NAME</bold>
                </Subtitle>
                <text>PED_MICEI2002_TESES</text>
            </header_item>
            
            <header_item>
                <Subtitle>
                    <bold> KEY_NAME</bold>
                </Subtitle>
                <text>PED_MICEI2002_TESES</text>
            </header_item>
            
            <header_item>
                <Subtitle>
                    <bold> KEY_NAME</bold>
                </Subtitle>
                <text>PED_MICEI2002_TESES</text>
            </header_item>
            
            
            <header_item>
                <Subtitle>
                    <bold> KEY_NAME</bold>
                </Subtitle>
                <text>PED_MICEI2002_TESES</text>
            </header_item>
            
            
            <header_item>
                <Subtitle>
                    <bold> KEY_NAME</bold>
                </Subtitle>
                <text>PED_MICEI2002_TESES</text>
            </header_item>
            
        </list_header>
    </Header>
    <Workteam>
        <Title>
            <bold>WorkTeam:</bold>
        </Title>
        <list_names>
            <names>
                <name>Diogo Miguel Pinto Rio</name>
                <id>a84752</id>
                <email>a84752@alunos.uminho.pt</email> 
            </names>
            
            <names>
                <name>Diogo Miguel Pinto Rio</name>
                <id>a84752</id>
                <email>a84752@alunos.uminho.pt</email> 
            </names>
            
            <names>
                <name>Diogo Miguel Pinto Rio</name>
                <id>a84752</id>
                <email>a84752@alunos.uminho.pt</email> 
            </names>
        </list_names>
    </Workteam>
    <Abstract>
        <Title>
            <bold>Abstract:</bold>
        </Title>
        <paragraph>
            <text>O XML, validado pelo schema, juntamente com o potente processamento via XSLT, permite dispor de facilidades acrescidas no tratamento de informação de uma forma standard e partilhável. Estas são, além de outras evidentes vantagens, as que abrem caminho a uma mais que provável evolução desta tecnologia nos círculos comerciais e de investigação. Outro facto importante, diz respeito à substituição de interfaces EDI por XML em aplicações bussiness oriented.</text>
        </paragraph>
        <paragraph>
            <text>O trabalho pretende definir uma estrutura expedita e funcional, passível de ser aplicada a um trabalho descritivo, como por exemplo uma tese. Não é objectivo do trabalho criar uma implementação sistemática de todos os objectos possíveis, mas sim criar algumas utilizações mais comuns para exemplificar a potência destas linguagens. </text>
        </paragraph>
    </Abstract>
    <Deliverables>
        <Title>
            <bold>Deliverables:</bold>
        </Title>
        <list_link>
            <link_item><link>wwww.somethingsomething.com</link></link_item>
            <link_item><link>wwww.somethingsomething.com</link></link_item>
            <link_item><link>wwww.somethingsomething.com</link></link_item>
        </list_link>
    </Deliverables>
</project_record>

=== DiogoRio/DAW2020/T3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project_record SYSTEM "pr.dtd">
<?xml-stylesheet type="text/css" href="pr.css"?> 
<project_record>
    <Main_Title>
        <Title>
            <text><bold>PROJECT RECORD</bold></text>
        </Title>
    </Main_Title>
    <Header>
        <list_header>
            <header_item>
                <Subtitle>
                    <bold>KEY_NAME:</bold>
                </Subtitle>
                <text>DAW2020_TPC_3</text>
            </header_item>
            
            <header_item>
                <Subtitle>
                    <bold>TITLE:</bold>
                </Subtitle>
                <text>DTD &amp; XSLT</text>
            </header_item>
            
            <header_item>
                <Subtitle>
                    <bold>SUBTITLE:</bold>
                </Subtitle>
                <text>Elaboração de um DTD e uma stylesheet XSLT que gere um website para um dataset </text>
            </header_item>
            
            <header_item>
                <Subtitle>
                    <bold>BEGIN DATE:</bold>
                </Subtitle>
                <text>Outubro 2020</text>
            </header_item>
            
            
            <header_item>
                <Subtitle>
                    <bold>END DATE:</bold>
                </Subtitle>
                <text>Novembro 2020</text>
            </header_item>
            
            
            <header_item>
                <Subtitle>
                    <bold>SUPERVISOR:</bold>
                </Subtitle>
                <text><link url="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</link></text>
            </header_item>
            
        </list_header>
    </Header>
    <Workteam>
        <Title>
            <text><bold>WorkTeam:</bold></text>
        </Title>
        <list_names>
            <names>
                <name>Diogo Miguel Pinto Rio</name>
                <id>a84752</id>
                <email>a84752@alunos.uminho.pt</email> 
            </names>
        </list_names>
    </Workteam>
    <Abstract>
        <Title>
            <text><bold>Abstract:</bold></text>
        </Title>
        <paragraph>
            <text>Neste TPC foi pedido para fazer um <bold>DTD</bold> e uma stylesheet <bold>XSLT</bold> que gere um website para um dataset de arqueossítios do NW português. </text>
        </paragraph>
        <paragraph>
            <text>O website fica estruturado com uma pagina principal de indice e uma pagina por cada registo. Durante a elaboração tive em conta que existem espaços em branco, os quais não são mostrados ao utilizador</text>
        </paragraph>
    </Abstract>
    <Deliverables>
        <Title>
            <text><bold>Deliverables:</bold></text>
        </Title>
        <list_link>
            <link_item><link url="https://github.com/DiogoRio/DAW2020/blob/main/T3/pr.dtd">https://github.com/DiogoRio/DAW2020/blob/main/T3/pr.dtd</link></link_item>
            <link_item><link url="https://github.com/DiogoRio/DAW2020/blob/main/T3/arq.dtd">https://github.com/DiogoRio/DAW2020/blob/main/T3/arq.dtd</link></link_item>
            <link_item><link url="https://github.com/DiogoRio/DAW2020/blob/main/T3/arq.xml">https://github.com/DiogoRio/DAW2020/blob/main/T3/arq.xml</link></link_item>
            <link_item><link url="https://github.com/DiogoRio/DAW2020/blob/main/T3/arq.xsl">https://github.com/DiogoRio/DAW2020/blob/main/T3/arq.xsl</link></link_item>
            <link_item><link url="https://github.com/DiogoRio/DAW2020/blob/main/T3/site/index.html">https://github.com/DiogoRio/DAW2020/blob/main/T3/site/index.html</link></link_item>
        </list_link>
    </Deliverables>
</project_record>
